name: Test
on: workflow_dispatch
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # Modified 1 line
          sudo apt install -y python-is-python3
      - run: |
          uv pip install -r requirements-tests.txt
      - run: |
          uv pip install --upgrade "pydantic>=2.0.2,<3.0.0"
      - run: |
          bash scripts/lint.sh
    env:
      TERM: xterm
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # Modified 1 line
          sudo apt install -y python-is-python3
      - run: |
          uv pip install -r requirements-tests.txt
          uv pip install --upgrade "pydantic>=2.0.2,<3.0.0"
          uv pip install "anyio[trio]<4.0.0"
      - run: |
          mkdir coverage
          bash scripts/test.sh
    env:
      LC_CTYPE: C.UTF-8
      TERM: xterm
