name: CI Workflow

on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Added 3 lines
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          uv pip install -r requirements-tests.txt
          uv pip install --upgrade "pydantic>=2.0.2,<3.0.0"

      - name: Run lint
        run: |
          bash scripts/lint.sh


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Added 3 lines
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          uv pip install -r requirements-tests.txt
          uv pip install --upgrade "pydantic>=2.0.2,<3.0.0"
          uv pip install "anyio[trio]<4.0.0"

      - name: Create coverage directory
        run: |
          mkdir coverage


      - name: Run tests
        run: |
          bash scripts/test.sh
